django_proj_I/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^nicelink/', include('nicelink.urls')),
    path('admin/', admin.site.urls),
]

django_proj_I/mysite/nicelink/urls.py
from django.conf.urls import url


from . import views

app_name = 'nicelink'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^link_list/$', views.link_list, name='link_list'),
    url(r'^user/$', views.register_view, name='register_view'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^link/(?P<original_link>.+)/$', views.redirect_to_oryginal_link, name='redirect_to_oryginal_link'),
    ]
# (?P<oryginal_link>)/

django_proj_I/mysite/polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django_proj_I/mysite/nicelink/models/Link.py
import random, string


from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class LinkManager(models.Manager):
    def create_link(self,oryginal_link_text):
        link = self.create(oryginal_link_text=oryginal_link_text, nice_link_text = self.link_generator())
        return link

    def link_generator( size=6, chars=string.ascii_letters + string.digits):
        text = 'localhost:8000/nicelink/' + ''.join(random.SystemRandom().choice(chars) for _ in range(size))
        print(text)
        return text


class Link(models.Model):
    class Meta:
        app_label = 'nicelink'

    oryginal_link_text = models.URLField(max_length=200)
    nice_link_text = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=1)

    objects = LinkManager()

    def __str__(self):
        reprezentation = self.oryginal_link_text+ " as " + self.nice_link_text
        return reprezentation

    def link_generator(self,size=6, chars=string.ascii_letters + string.digits):
        self.nice_link_text = ''.join(random.SystemRandom().choice(chars) for _ in range(size))
        return self.nice_link_text

django_proj_I/mysite/nicelink/models/User.py
from django.db import models


from .Link import Link


class UserModel(models.Model):
    class Meta:
        app_label = 'nicelink'

    username = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=30)
    email = models.EmailField(max_length=60, unique= True)
    fullname = models.CharField(max_length=40)
    # links = models.ForeignKey(Link, on_delete=models.CASCADE)

    def __str__(self):
        return '<Username: %r>' %self.username

django_proj_I/mysite/nicelink/forms/site_forms.py
from django import forms


class LinkForm(forms.Form):
    oryginal_link = forms.URLField(label='Your link', max_length=200)
    nice_link = ''

django_proj_I/mysite/nicelink/forms/user_forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, get_user_model
from django import forms

from ..models.User import UserModel


class UserRegisterForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'password']

    def clean(self):
        # cleaned_data = super(UserForm, self).clean()
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

# User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Incorrect Username or password")
        if not user.check_password(password):
            raise forms.ValidationError("Incorrect Username or password")
        return super(UserLoginForm, self).clean(*args, **kwargs)

django_proj_I/mysite/nicelink/views/site_views.py
from django.shortcuts import render, get_object_or_404
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required



from ..models.Link import Link, LinkManager
from ..forms import LinkForm
from ..forms import UserRegisterForm


def index(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LinkForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # link = Link.objects.create_link(form.cleaned_data['oryginal_link'])

            flag = True
            while flag:
                try:
                    link = Link(oryginal_link_text=form.cleaned_data['oryginal_link'],
                                nice_link_text=LinkManager.link_generator(),
                                user = None)
                    if request.user.is_authenticated:
                        link = Link(oryginal_link_text = form.cleaned_data['oryginal_link'],
                                    nice_link_text = LinkManager.link_generator(),
                                    user = request.user)
                        print(request.user.id)
                        link.save()
                    flag =False
                except IntegrityError:
                   print(IntegrityError)

            messages.success(request, 'Link generated')
            return render(request, 'nicelink/index.html', {'form': form,
                                                           'link':link})
    else:
        form = LinkForm()

    return render(request, 'nicelink/index.html', {'form': form})

@login_required(login_url='/nicelink/login/')
def link_list(request):
    links = Link.objects.filter(user = request.user)
    links = reversed(links)
    return render(request, 'nicelink/link_list.html',{'links' : links})

def redirect_to_oryginal_link(request, original_link):
    print(original_link)
    return redirect(original_link)

def user_register(request):

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UserRegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # link = Link.objects.create_link(form.cleaned_data['oryginal_link'])
            print('form valid')

            flag = True
            while flag:
                try:
                    form.clean()
                    form.save()
                    print('done')
                    flag = False
                except IntegrityError:
                    print('ERROR')


            return HttpResponseRedirect(reverse('nicelink:index'))
    else:
        form = UserRegisterForm()

    return render(request, 'nicelink/user.html', {'form': form})

django_proj_I/mysite/nicelink/views/user_views.py
from django.shortcuts import render, get_object_or_404
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout

from ..forms import UserRegisterForm, UserLoginForm




def register_view(request):
    title = 'Register'
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UserRegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # link = Link.objects.create_link(form.cleaned_data['oryginal_link'])
            print('form valid')
            try:
                user = form.save(commit=False)
                password = form.cleaned_data.get('password')
                user.set_password(password)
                user.save()
                flag = False
            except IntegrityError:
                print(IntegrityError)
            return HttpResponseRedirect(reverse('nicelink:index'))
    else:
        form = UserRegisterForm()
    return render(request, 'nicelink/user.html', {'form': form})


def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request,user)
        if next:
            return redirect(next)
    return render(request, 'nicelink/login.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('nicelink:index')

django_proj_I/mysite/nicelink/templates/nicelink/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatibile" content="IE=edge">
    <meta name="viewport" content="width=device-width", intial-sacle="1">
    <title>{% block title %}{% endblock %}</title>

    <!--own css -->

    <!--Bootstrap-->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% block head %}

{% endblock %}


    <div class="container">
        <div class="row">
             <div class="col-md-3">
            {% block sidebar %}{% endblock %}


             </div>
            <div class="col-md-8">
            {% block content %}{% endblock %}
            </div>
        </div>


        <div class="col-md-offset-3 col-md-6">

        <footer>

            &copy; Copyright 2017

        </footer>

    </div>


    </div>


    <!--jQuery for Bootsrtap-->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <!--Bootstrap JS-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</body>
</html>

django_proj_I/mysite/nicelink/templates/nicelink/index.html
{% extends 'nicelink/base.html' %}



{% block head %}
<center><h3>Home Page</h3></center>
{% endblock %}


{% block content %}
<form action="{% url 'nicelink:index' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br>
    Your nice link: {{ link.nice_link_text }}
    <br>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

{% block sidebar %}
<a type="button" href="{% url 'nicelink:link_list' %}"
                            class="btn btn-primary btn-lg btn-block">Link List</a>
<a type="button" href="{% url 'nicelink:register_view' %}"
                            class="btn btn-primary btn-lg btn-block">User Register</a>

{% endblock %}

django_proj_I/mysite/nicelink/templates/nicelink/link_list.html
{% extends 'nicelink/base.html' %}



{% block head %}
<center><h3>Link List</h3></center>
{% endblock %}


{% block sidebar %}
<a type="button" href="{% url 'nicelink:index' %}"
                            class="btn btn-primary btn-lg btn-block">Main Page</a>

{% endblock %}


{% block content %}


<ul>
    {% for link in links %}
    <li>
        {{ link.oryginal_link_text }}
        - as -
        <a href="{% url 'nicelink:redirect_to_oryginal_link' link.oryginal_link_text %}" target="_blank">{{ link.nice_link_text }}</a>
        <hr>
    </li>
    {% endfor %}
</ul>
{% endblock %}

django_proj_I/mysite/nicelink/templates/nicelink/login.html
{% extends 'nicelink/base.html' %}



{% block head %}
<center><h3>Login</h3></center>
{% endblock %}

{% block content %}
<form action="{% url 'nicelink:login_view' %}" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Login" />

</form>
{% endblock %}


{% block sidebar %}
<a type="button" href="{% url 'nicelink:link_list' %}"
                            class="btn btn-primary btn-lg btn-block">Link List</a>
<a type="button" href="{% url 'nicelink:index' %}"
                            class="btn btn-primary btn-lg btn-block">Main Page</a>

{% endblock %}

django_proj_I/mysite/nicelink/templates/nicelink/user.html
{% extends 'nicelink/base.html' %}



{% block head %}
<center><h3>Link List</h3></center>
{% endblock %}

{% block content %}
<form action="{% url 'nicelink:register_view' %}" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <br>
    <input type="submit" value="Submit" />

</form>
{% endblock %}


{% block sidebar %}
<a type="button" href="{% url 'nicelink:link_list' %}"
                            class="btn btn-primary btn-lg btn-block">Link List</a>
<a type="button" href="{% url 'nicelink:index' %}"
                            class="btn btn-primary btn-lg btn-block">Main Page</a>

{% endblock %}